development:
  adapter: mysql
  database: badpoetry_development
  username: root
  password:
  host: 127.0.0.1

production:
  adapter: mysql
  database: badpoetry
  username: badpoetry
  password: bad000
  host: mysql.fishbulb.info
